# This is a basic workflow to help you get started with Actions

name: Node Native CI

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    name: Build and test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Omniorb 4
        run: sudo apt-get install libomniorb4-dev

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Prepare environment
        run: yarn
        
      - name: Build
        run: yarn build

      - name: Lint and test
        run: yarn test

      - name: Package
        run: npx pkg package.json

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ondemand-build
          files: |
            dist/*

  validate-prod-dependencies:
    name: Validate production dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Omniorb 4
        run: sudo apt-get install libomniorb4-dev
      - name: Prepare Environment
        run: yarn
        env:
          CI: true
      - name: Validate production dependencies
        run: |
          if ! git log --format=oneline -n 1 | grep -q "\[ignore-audit\]"; then
            yarn validate:dependencies
          else
            echo "Skipping audit"
          fi
        env:
          CI: true

